### ISSUE TITLE
Crashes upon entering ancient world (perhaps an incompatibility with another mod?)

### ISSUE THREAD

**Issue by RollRim** [Artur114Projects/Thaumcraft_Return_of_the_ancients#3]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  SimpleDifficulty ASM (SimpleDifficulty-1.12.2-0.3.9.jar)
  Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-2.1.11.jar)
  Persistency (persistency-1.2.0.jar)
  clothesline-hooks (clothesline-hooks-1.12.2-0.0.1.2.jar)
  OTGCorePlugin (OTG-Core.jar)
  AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
  TransformLoader (DynamicSurroundings-1.12.2-3.6.3.jar)
  CoreMod (ClassicSwordBlocking-1.12.2-1.0.6.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 11/10/24 3:45 PM
Description: Exception while ticking a block

java.lang.NoClassDefFoundError: net/minecraft/world/World$2
	at net.minecraft.world.World.func_190524_a(World.java:557)
	at net.minecraft.world.World.func_175685_c(World.java:495)
	at net.minecraft.world.World.func_175722_b(World.java:440)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:381)
	at net.minecraft.world.World.func_180501_a(World.java:361)
	at net.minecraft.world.World.func_175698_g(World.java:398)
	at net.minecraft.block.BlockFalling.func_176503_e(BlockFalling.java:66)
	at net.minecraft.block.BlockFalling.func_180650_b(BlockFalling.java:44)
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:737)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.World.func_190524_a(World.java:557)
	at net.minecraft.world.World.func_175685_c(World.java:495)
	at net.minecraft.world.World.func_175722_b(World.java:440)
	at net.minecraft.world.World.markAndNotifyBlock(World.java:381)
	at net.minecraft.world.World.func_180501_a(World.java:361)
	at net.minecraft.world.World.func_175698_g(World.java:398)
	at net.minecraft.block.BlockFalling.func_176503_e(BlockFalling.java:66)
	at net.minecraft.block.BlockFalling.func_180650_b(BlockFalling.java:44)

-- Block being ticked --
Details:
	Block: minecraft:gravel
	Block location: World: (-1328,46,-528), Chunk: (at 0,2,0 in -83,-33; contains blocks -1328,0,-528 to -1313,255,-513), Region: (-3,-2; contains chunks -96,-64 to -65,-33, blocks -1536,0,-1024 to -1025,255,-513)
Stacktrace:
	at net.minecraft.world.WorldServer.func_72955_a(WorldServer.java:737)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:223)

-- Affected level --
Details:
	Level name: world
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 2200 Drop: 0
	Level seed: 1179041630601966526
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (232,64,248), Chunk: (at 8,4,8 in 14,15; contains blocks 224,0,240 to 239,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 4588 game time, 4588 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 30455 (now: false), thunder time: 90940 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 729911168 bytes (696 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 12, tcache: 94, allocated: 0, tallocated: 0
	FML: ~~ERROR~~ NoClassDefFoundError: net/minecraftforge/common/util/TextTable$1
	Loaded coremods (and transformers): 
SimpleDifficulty ASM (SimpleDifficulty-1.12.2-0.3.9.jar)
  com.charles445.simpledifficulty.asm.SimpleDifficultyASM
Thaumic Augmentation Core Plugin (ThaumicAugmentation-1.12.2-2.1.11.jar)
  thecodex6824.thaumicaugmentation.core.TATransformer
Persistency (persistency-1.2.0.jar)
  zone.rong.persistency.Persistency$ClientTransformer
clothesline-hooks (clothesline-hooks-1.12.2-0.0.1.2.jar)
  com.jamieswhiteshirt.clothesline.hooks.plugin.ClassTransformer
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.excluded.OTGClassTransformer
AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
TransformLoader (DynamicSurroundings-1.12.2-3.6.3.jar)
  
CoreMod (ClassicSwordBlocking-1.12.2-1.0.6.jar)
  
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Pulsar/harvesttweaks loaded Pulses: 
		- blocks (Enabled/Forced)
		- items (Enabled/Forced)

	Pulsar/inspirations loaded Pulses: 
		- InspirationsShared (Enabled/Forced)
		- InspirationsBuilding (Enabled/Not Forced)
		- InspirationsUtility (Enabled/Not Forced)
		- InspirationsTools (Enabled/Not Forced)
		- InspirationsRecipes (Enabled/Not Forced)
		- InspirationsTweaks (Enabled/Not Forced)
		- InspirationsShared (Enabled/Forced)
		- LeatherWorks (Enabled/Not Forced)

	No Tree Punching: You are not running an official build. This version will NOT be supported by the author.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['RollRim'/2341, l='world', x=0.00, y=244.00, z=0.00]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_G5
	OptiFine Build: 20210124-142939
	Render Distance Chunks: 6
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 31.0.101.4502
	OpenGlRenderer: Intel(R) RaptorLake-S Mobile Graphics Controller
	OpenGlVendor: Intel
	CpuCount: 20

**Comment by RollRim** [comment]
Rejoining after the crash seems to fix it

**Comment by Artur114Projects** [comment]
Hello I think the problem is in the compatibility of mods, but my mod has nothing to do with it :) the crash was caused by the fact that gravel fell and the piece of code responsible for its fall was missing and Minecraft crashed, this may be due to a conflict of optimization mods or not because of missing libraries that the authors, as the best people, did not indicate in the dependencies

**Comment by RollRim** [comment]
I had a few other crashes occur and removing this mod seemed to fix it. I tried using the mod by itself (along with Thaumcraft obviously) and the crashes stopped so it must be some sort of compatibility issue?
